import os

FASTAPI_PASSWORD = os.getenv("FASTAPI_PASSWORD", 'password')
NOTION_ACCESS_KEY = os.getenv("NOTION_ACCESS_KEY")
NOTION_DATABASE_ID = os.getenv("NOTION_DATABASE_ID")
FASTAPI_ALLOWED_HOSTS = os.getenv("FASTAPI_ALLOWED_HOSTS", "")
